# Generated by Django 5.1.7 on 2025-03-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36, unique=True)),
                ('worker_code', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('work_code', models.CharField(max_length=50)),
                ('executor', models.CharField(max_length=100)),
                ('intervals', models.TextField(default='[]')),
                ('current_start', models.CharField(blank=True, max_length=50, null=True)),
                ('time_left', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
