# Generated by Django 5.1.7 on 2025-03-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='work_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
