# Generated by Django 5.1.7 on 2025-03-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_worksession_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='initial_time_left',
            field=models.IntegerField(default=0),
        ),
    ]
