# Generated by Django 5.1.7 on 2025-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_worksession_initial_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='initial_time',
            field=models.IntegerField(default=0),
        ),
    ]
