# Generated by Django 5.1.7 on 2025-03-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_worksession_initial_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='initial_time',
        ),
    ]
