# Generated by Django 5.1.7 on 2025-03-31 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_worksession_last_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='last_action',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='pause_reason_code',
        ),
        migrations.AlterField(
            model_name='worksession',
            name='current_start',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='time_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkSessionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.CharField(blank=True, max_length=20, null=True)),
                ('end', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='service_app.worksession')),
            ],
        ),
    ]
