# Generated by Django 5.1.7 on 2025-03-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_remove_worksession_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код причины')),
                ('description', models.CharField(max_length=100, verbose_name='Описание причины')),
            ],
            options={
                'verbose_name': 'Причина паузы',
                'verbose_name_plural': 'Причины паузы',
            },
        ),
    ]
