# Generated by Django 5.1.7 on 2025-04-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_pausereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
