# Generated by Django 5.1.7 on 2025-04-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0009_worksession_is_finished'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(fields=('executor', 'order_number', 'work_code'), name='unique_work_session'),
        ),
    ]
