# Generated by Django 5.1.7 on 2025-04-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_worksession_unique_work_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worksession',
            name='unique_work_session',
        ),
    ]
