# Generated by Django 5.1.7 on 2025-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0012_worksession_unique_work_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worksession',
            name='unique_work_session',
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(fields=('executor', 'order_number', 'work_code', 'intervals'), name='unique_work_session'),
        ),
    ]
